### ISSUE TITLE
Unable to find search period radio box

### ISSUE THREAD

**Issue by richi235** [hoffie/dkb-visa#15]
Running dkb.py as usual results in: 

```
Navigating to 'Umsätze'...
Selecting transactions in time frame 03.03.2017 - 28.05.2017...
Traceback (most recent call last):
  File "./dkb.py", line 427, in <module>
    fetcher.select_transactions(args.cardid, from_date, args.to_date)
  File "./dkb.py", line 190, in select_transactions
    self._select_all_transactions_from(form, from_date, to_date)
  File "./dkb.py", line 115, in _select_all_transactions_from
    raise RuntimeError("Unable to find search period radio box")
RuntimeError: Unable to find search period radio box
```

**Comment by hoffie** [comment]
Hi richi235,

could you try again after pulling the latest version?
Based on your notification, I have adapted the form selection logic after dkb.de apparently changed form field names again. ;)

Kind regards,
Christian

**Comment by richi235** [comment]
Hi,
I just pulled this commit and works great :)

Thank you for your effort and work
